Store package version in code; minor refactoring

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -15,11 +15,11 @@ jobs:
     - uses: actions/checkout@v4
 
     - name: Setup Python
-      uses: actions/setup-python@v4
+      uses: actions/setup-python@v5
       with:
         python-version: 3.12
 
-    - name: Install dependencies
+    - name: Install build dependencies
       run: |
         python -m pip install --upgrade pip
         pip install build twine
@@ -31,7 +31,7 @@ jobs:
       env:
         TWINE_USERNAME: __token__
         TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
-      run:
+      run: |
         twine upload dist/*
 
   create-release:
@@ -42,16 +42,20 @@ jobs:
     steps:
     - uses: actions/checkout@v4
 
-    - uses: SebRollen/toml-action@v1.0.2
+    - name: Read package version
       id: read_version
-      with:
-        file: pyproject.toml
-        field: project.version
+      run: |
+        version=$(grep "^__version__" src/kataloger/__init__.py | sed -E 's/^.*"([0-9A-Za-z\-_+.]+)".*$/\1/')
+        if [ -z "$version" ]; then
+          echo "ERROR: Can't find package version!"
+          exit 1
+        fi
+        echo "::set-output name=package_version::$version"
 
     - uses: softprops/action-gh-release@v1
       name: Create release
       with:
         body_path: ${{ github.workspace }}/changelog.md
-        name: v${{ steps.read_version.outputs.value }}
-        tag_name: v${{ steps.read_version.outputs.value }}
+        name: v${{ steps.read_version.outputs.package_version }}
+        tag_name: v${{ steps.read_version.outputs.package_version }}
         token: ${{ secrets.GITHUB_TOKEN }}
